name: Build && Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [spiderfoot, spiderfoot-full]
        include:
          - type: spiderfoot
            file: Dockerfile
            tag: latest
          - type: spiderfoot-full
            file: Dockerfile.full
            tag: latest-full
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push 
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: ${{ steps.branch-name.outputs.current_branch }}-${{ matrix.tag }}
        platforms: linux/amd64
        file: ${{ matrix.file }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        